config/routes.rb
Rails.application.routes.draw do
  #resources :players
  resources :some_things
  resources :winners
  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

  resources :typos do
  resources :players
end
  root 'typos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/some_thing.rb
class SomeThing < ApplicationRecord
end

app/controllers/some_things_controller.rb
class SomeThingsController < ApplicationController
  before_action :set_some_thing, only: [:show, :edit, :update, :destroy]

  # GET /some_things
  # GET /some_things.json
  def index
    @some_things = SomeThing.all
  end

  # GET /some_things/1
  # GET /some_things/1.json
  def show
  end

  # GET /some_things/new
  def new
    @some_thing = SomeThing.new
  end

  # GET /some_things/1/edit
  def edit
  end

  # POST /some_things
  # POST /some_things.json
  def create
    @some_thing = SomeThing.new(some_thing_params)

    respond_to do |format|
      if @some_thing.save
        format.html { redirect_to @some_thing, notice: 'Some thing was successfully created.' }
        format.json { render :show, status: :created, location: @some_thing }
      else
        format.html { render :new }
        format.json { render json: @some_thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /some_things/1
  # PATCH/PUT /some_things/1.json
  def update
    respond_to do |format|
      if @some_thing.update(some_thing_params)
        format.html { redirect_to @some_thing, notice: 'Some thing was successfully updated.' }
        format.json { render :show, status: :ok, location: @some_thing }
      else
        format.html { render :edit }
        format.json { render json: @some_thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /some_things/1
  # DELETE /some_things/1.json
  def destroy
    @some_thing.destroy
    respond_to do |format|
      format.html { redirect_to some_things_url, notice: 'Some thing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_some_thing
      @some_thing = SomeThing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def some_thing_params
      params.require(:some_thing).permit(:val)
    end
end

app/helpers/some_things_helper.rb
module SomeThingsHelper
end

app/views/some_things/_form.html.erb
<%= form_for(some_thing) do |f| %>
  <% if some_thing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(some_thing.errors.count, "error") %> prohibited this some_thing from being saved:</h2>

      <ul>
      <% some_thing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :val %>
    <%= f.text_field :val , class:"form-control" %>
  </div>

  <div class="actions">
    <%= f.submit :booboo, class:"btn btn-default"%>
  </div>
<% end %>

app/views/some_things/edit.html.erb
<h1>Editing Some Thing</h1>

<%= render 'form', some_thing: @some_thing %>

<%= link_to 'Show', @some_thing , class:"btn btn-xs btn-default" %> |
<%= link_to 'Back', some_things_path , class:"btn btn-xs btn-default"  %>

app/views/some_things/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Some Things</h1>

<table class="table table-responsive">
  <thead>
    <tr>
      <th>Val</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @some_things.each do |some_thing| %>
      <tr>
        <td><%= some_thing.val %></td>
        <td><%= link_to 'Show', some_thing , class:"btn btn-xs btn-danger" %></td>
        <td><%= link_to 'Edit', edit_some_thing_path(some_thing) , class:"btn btn-xs btn-danger" %></td>
        <td><%= link_to 'Destroy', some_thing, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-xs btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Some Thing', new_some_thing_path , class:"btn btn-xs btn-danger" %>

app/views/some_things/new.html.erb
<h1>New Some Thing</h1>

<%= render 'form', some_thing: @some_thing %>

<%= link_to 'Back', some_things_path , class:"btn btn-xs btn-danger" %>

app/views/some_things/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">

<div class="panel-heading">some_thing</div>

<div class="panel-body">


<p>
  <strong>Val:</strong>
  <%= @some_thing.val %>
</p>


</div>

<div class="panel-footer">

<%= link_to 'Edit', edit_some_thing_path(@some_thing) ,class:"btn btn-xs btn-danger" %> |
<%= link_to 'Back', some_things_path , class:"btn btn-xs btn-danger" %>

</div></div>