config/routes.rb
Rails.application.routes.draw do
  #resources :players
  resources :some_things
  resources :winners
  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

  resources :typos do
  resources :players
end
  root 'typos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/typo.rb
class Typo < ApplicationRecord
end

app/controllers/typos_controller.rb
class TyposController < ApplicationController
  before_action :set_typo, only: [:show, :edit, :update, :destroy]

  # GET /typos
  # GET /typos.json
  def index
    @typos = Typo.all
  end

  # GET /typos/1
  # GET /typos/1.json
  def show
  end

  # GET /typos/new
  def new
    @typo = Typo.new
  end

  # GET /typos/1/edit
  def edit
  end

  # POST /typos
  # POST /typos.json
  def create
    @typo = Typo.new(typo_params)

    respond_to do |format|
      if @typo.save
        format.html { redirect_to @typo, notice: 'Typo was successfully created.' }
        format.json { render :show, status: :created, location: @typo }
      else
        format.html { render :new }
        format.json { render json: @typo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /typos/1
  # PATCH/PUT /typos/1.json
  def update
    respond_to do |format|
      if @typo.update(typo_params)
        format.html { redirect_to @typo, notice: 'Typo was successfully updated.' }
        format.json { render :show, status: :ok, location: @typo }
      else
        format.html { render :edit }
        format.json { render json: @typo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /typos/1
  # DELETE /typos/1.json
  def destroy
    @typo.destroy
    respond_to do |format|
      format.html { redirect_to typos_url, notice: 'Typo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_typo
      @typo = Typo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def typo_params
      params.require(:typo).permit(:name, :stuff)
    end
end

app/helpers/typos_helper.rb
module TyposHelper
end

app/views/typos/_form.html.erb
<%= form_for(typo) do |f| %>
  <% if typo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(typo.errors.count, "error") %> prohibited this typo from being saved:</h2>

      <ul>
      <% typo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name , class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :stuff %>
    <%= f.text_field :stuff , class:"form-control" %>
  </div>

  <div class="actions">
    <%= f.submit :create, class:"btn btn-default"%>
  </div>
<% end %>

app/views/typos/edit.html.erb
<h1>Editing Typo</h1>

<%= render 'form', typo: @typo %>

<%= link_to 'Show', @typo , class:"btn btn-xs btn-default" %> |
<%= link_to 'Back', typos_path , class:"btn btn-xs btn-default"  %>

app/views/typos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Typos</h1>

<table class="table table-responsive">
  <thead>
    <tr>
      <th>Name</th>
      <th>Stuff</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @typos.each do |typo| %>
      <tr>
        <td><%= typo.name %></td>
        <td><%= typo.stuff %></td>
        <td><%= link_to 'Show', typo , class:"btn btn-xs btn-danger" %></td>
        <td><%= link_to 'Edit', edit_typo_path(typo) , class:"btn btn-xs btn-danger" %></td>
        <td><%= link_to 'Destroy', typo, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-xs btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Typo', new_typo_path , class:"btn btn-xs btn-danger" %>

app/views/typos/new.html.erb
<h1>New Typo</h1>

<%= render 'form', typo: @typo %>

<%= link_to 'Back', typos_path , class:"btn btn-xs btn-danger" %>

app/views/typos/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-primary">

<div class="panel-heading">Typo</div>

<div class="panel-body">


<p>
  <strong>Name:</strong>
  <%= @typo.name %>
</p>


<p>
  <strong>Stuff:</strong>
  <%= @typo.stuff %>
</p>


</div>

<div class="panel-footer">

<%= link_to 'Edit', edit_typo_path(@typo) ,class:"btn btn-xs btn-danger" %> |
<%= link_to 'Back', typos_path , class:"btn btn-xs btn-danger" %>

</div>
</div>